- name: Build And Deploy
  id: builddeploy
  uses: Azure/static-web-apps-deploy@v1
  with:
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
    action: "upload"
    app_location: "/"         # tu HTML está en la raíz
    api_location: ""          # no hay backend
    output_location: "/"      # crítico: sube la raíz tal cual
    app_build_command: ""     # <--- desactiva cualquier build
