name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # 1️⃣ Clona el repositorio
      - uses: actions/checkout@v3

      # 2️⃣ Despliega en Azure Static Web Apps
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "/"          # tus archivos HTML están en la raíz
          api_location: ""           # no hay backend
          output_location: "/"       # sube la raíz tal cual
          app_build_command: ""      # desactiva cualquier build
