name: Deploy Static HTML to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Clona el repositorio
      - uses: actions/checkout@v3

      # 2️⃣ Despliega archivos estáticos
      - name: Deploy Static HTML
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "/"          # archivos HTML en la raíz
          api_location: ""           # no hay backend
          output_location: "/"       # sube la raíz tal cual
          skip_app_build: true       # ❌ evita cualquier intento de build
